### ISSUE TITLE
Fix dollar symbol $ on the dashboard screen

### ISSUE THREAD

**Issue by desezde** [Deutsche-Boerse-Risk/DAVe#14]
On dashboard screen is still a dollar $ symbol for Euro € as a clearing currency.

**Comment by scholzj** [comment]
The currency symbol in the donut charts is complicated ... right now, the chart is actually mixing together different currencies, because margin requirement and shortfall / surplus are not in the clearing currency (AFAIK). Only the margin call is in the clearing currency. Another problem with these charts is probably how they handle negative and positive values.

Because the charts anyway don't make much sense, I simply removed the dollar sign, which was clearly incorrect. But didn't replaced it with any other sign. Once we have a real charts which deliver some value, we should fine-tune them to show the correct currency.
